NAME =  replace

SRC = main.cpp

OBJC = $(SRC:.cpp=.o)

RM = rm -rf 
abouabba = c++
CPPFLAGE = -Wall -Wextra -Werror -std=c++98 

all: ${NAME}

%.o: %.cpp 
	${abouabba} ${CPPFLAGE} -c $< -o $@ 

${NAME}: ${OBJC}
	${abouabba} ${CPPFLAGE} -o ${NAME} ${OBJC}

clean:
	${RM} ${OBJC}

fclean: clean 
	${RM} ${NAME}

re: fclean all